name: Callable - Quick Checks

on:
  workflow_call:

jobs:
  quick-checks:
    name: Quick Checks - ${{ matrix.os }}, ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16.15.1]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.3
        with:
          path: |
            ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Scan Production Dependencies for Vulnerabilities
        run: pnpm audit:prod

      - name: Deep Lint
        run: pnpm lint

      - name: Vitest Unit and Integration Test Runner
        run: pnpm test:vitest:ci

      # Disabled until Cypress CT tests are added
      # - name: Cypress PNPM Patch
      #   run: cp pnpm-lock.yaml package-lock.json

      # - name: Cypress Component Test Runner
      #   uses: cypress-io/github-action@v4
      #   with:
      #     component: true
      #     install: false
